sudo: required
services:
  - docker
language: java
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=sr123/fetcher:fetcher-1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
    - secure: "eic/WiVd0nMA9g4UDrx3eO1u4gP1KVcqKS5WjZXejHAxTimLsb+dL5c7gR+hZJsFpIxC4z39eDR6A8c/bi/2g83E2iQLTfizTFepEKun+VwszSX+ocIggrKDXDqHuBZHEKf0L2pWWAT2BXkRaXBJUTAEOESkMmSsFQmQiLaIDYg4Etpz31EiyrSy+IH8qEahL/SzCVJJLMkxhHTFl0YQF/GqqALA66LSsJNJcwBhlGIE9qNgnH+y7hSYPgqPDbRCzXZ5teWOMnf41S1hlu+XR4Pl1vjnk1H1XYFBLrFoGeE1BLjYXehf6n8sAVFfqA9QhCatmEj7oXaytLmSNbFtBABhsdbAng5SkAQ+YFoT7isodxccLWDbPOTsPJywSty63zQnPAFrJWZ4RDRMlihGnz86fDYom8fvq25aS332ykPVvabNMKKA0kkzfuOJpR7Cd091p7e3xFyzA4pdCPgjqa0+b9GB96tu67a742MHPiYGKuVmWqL4Yf2xRF3gy0BHMPvE65vFTmrlCb5aL6cTxNwvTTOskqT0JKl6OFEnNR9vThwt62k0AFOh0rlZcfMG+UDCy4eFQ6w5fFkFq9s8YMaOVkmCbmQ1z/DVQiaeZwYfcr8iD5EhYFl6A9DuLnL60P/XPUMByHxZKTC0fKD+C+t6jpoS1zjnjknlnkvNfEQ="
    - secure: "PNHU6ddOZ6vYIGAfG1ncVNtGXtE7OU6/v5CGSAIL63+/7hFCAJZV00KLcUl6iNMBwWkTnDE+lamXdpWt+MgtUJlu524EVqQ+zscaENUSdLAe7NTHVXoxhw7e027ku8y6cvzUjhlN70NCzOWE6W8bHd0p4VRex5iqot3HktlOH6Tv7d6A1APYD3bqz6FbVscPtGNI1mWv8JKe+1YZWCrX92TkAgftQr5C3BV3rQO6fK9/xFhKgSpGLXLcBGFEQQ6ux8AcQdq7B/VpUAeqa1ENwMYQhKIENlfjlZyJDLnHykzmsXKjgTB2rO71nVC0f9OTq7J/pswNacuZHqL7KIymFMA/+laNQ/En6tJj6hktBd07x+EnF1/Y/PAsQ2rjbPkigS/z0l+VDAamXPpdbF8KCY0lqz5U5m06BDI2zZk6RF1RcR5zpQ7qZl5lOpUrLStPj6bB+6u6X9ksIjzkdHnb4mdBjRV2k+8sBY55l+NQgA+gEKFATQ0eeLFtiNtCDEq8CpYqEham2lQ5+06NGllCRIsBHzBdEoVKYaqlXOvtgy61xnA7DWRTidYeNvOxrSsGiRCHaICyac54Oq1IJQIQKxwTfu/qdCH9JNsZBuNOafIQEAaecq/VaobVX58GnypPPjcHPM0javsQdXhmYH65in3L0NCSdYK49YwJC53NtN8="
script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"