sudo: required
services:
  - docker
language: java
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=sr123/fetcher:fetcher-1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
    - secure: "qy7HjF8z1FWyjQ7nQkO/U2InCgGQXsdSzpjIe4KhH8bJB6cWW/r+F/WA33vnLvJqlmYr7NPS+IViiGeXtOBDlV9LJaZxRdu89ID1J5RUMGy65fxqqWfokIdM9I0STOKosV1c9RYWD+Qg7azJ5Cq7uSn0lMjt1aPhCn0EquGb5H4WMQg/HthD+3u1BkPBiuU/0DVXjKP1YBA43PtQdyUTF3BeoTp2qjJC90WigWFApSHAU8DkrvWPWZ9OjYoylt9pXXBuB5J3cnw5tvngLL8c1gGZ3ae0ZCxoUSPbnWS9PcQd2ZiUZmAr/51rhqJcXqieo53J4aKIVAG2vyvNufWwOgqB7zsoJyhhbUMnhRCirP6oioYoot8uXBG2lW9+d/0RPoL9/u/GACqqXwz4vAThtrNnf1GjWWrY3vFtOlx2CzizwLvz2caTAPrTPlBsOhzdjQ4EybqW957G+6980UJ8GqMCKD8JoWw46CGXjmNH9MR1ZHuh07G101no1H8ZlyT7KqVD4VbEe7joUYbK+/HoshfObJjP3oL/vc/oIMwAwy0P8UUz1+ebG6NDVksUi9EOVfcCrMT5jHwp+eIF/q1Dgv3UB0UKMVEo1PXggkHEqUa00Os53u1/2C2dlJfN+zJm7NxOx45WtBfre4HDuGh/tbe7VFB7Fzx8CMV2Y6iJBas="
    - secure: "1QesITpyOo+PtUWnBYLVhkbRYEM3R9/xpQDGvobRrcDcnqp1pyIMEgNj4F6WuteXNZhI+YuqSnqfhaDrBsKSZQs0s/w7Sj7S23RVO9xT9FM8ssrgaw9cmAe7wJKt1+H4Ok0tDYFdnHhZQRgZcJaIYq1D9tAnUgn28FgS/FjxBu90cpbgzJLtXTYuNDjWaXJE4v9hARwv12WJMWzf5hXX5gbTc1JUzmYPbkKmvcStBAcGlpYNLy3Fe911rTmDopFJ8/Y3jOBlreAE01798yQ5vX+GjXyXZmpGoLnrQN55AyPkMX6/5q6ptovTZq3PGRolx3vH77BP3QrqDADEvJO74/IdZyzJ9hxEOQhwV6xFmuE72OWX3jti/y4aoN2mNeTLcPyyTfPro93S9F1c0GcZRsPR70eY1n8izpY1Jgk6zfhTSVsCCSga7ATTH637aIeo3pfqUbiR8ySYK5nS/tn75jEsMMidl0E7pRyTndQ/V0+SdeI9hl11oLagU9MLkvh2udnG0DkZqGBbVIsEY3MeQ0Gij/Klc7akCqCZY6l4FIc9DzrKOTdOOM6gbpLDOCtzFlS+3HH5XUZA5H2dgox0UunOwcbyabxPPLSu7gZb5QJ5h61Ur3r2cI9GhLnD0fzv8yloClRRYfPRixkP2XN8m1CigByvrDg8uGWGfP+Yvwo="
script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"