kumuluzee:
  name: ai
  env:
    name: test
  version: 1.0.0
  server:
    http:
      port: 8082
  #datasources:
  #  - jndi-name: jdbc/ImageMetadataDS
  #    connection-url: jdbc:postgresql://192.168.29.109:5432/image-metadata
  #    username: dbuser
  #    password: postgres
  #    max-pool-size: 20
  discovery:
    etcd:
      hosts: http://34.89.142.186:2379/
  health:
    servlet:
      mapping: /ai/health
      enabled: true
    logs:
      enabled: true
    checks:
      etcd-health-check:
        connection-url: http://34.89.142.186:2379/health
  metrics:
    web-instrumentation:
      - name: ai-api
        url-pattern: /ai/api/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="4b7940ff-723b-490b-9dab-5ae0e1e920ca-ls.logit.io"
                                    port="16785" protocol="tcp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="trace"/>
                                        <AppenderRef ref="logstash" level="trace"/>
                                    </Root>
                                </Loggers>
                            </Configuration>'
configuration-properties:
  ai:
    enabled: true