kumuluzee:
  name: fetcher
  env:
    name: test
  version: 1.0.0
  server:
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/blockerstorage
      connection-url: jdbc:postgresql://34.65.73.233/blockerstorage
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://34.65.200.108:2379/
  health:
    servlet:
      mapping: /fetcher/health
      enabled: true
    logs:
      enabled: true
    checks:
      etcd-health-check:
        connection-url: http://34.65.200.108:2379/health
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/blockerstorage
  metrics:
    web-instrumentation:
      - name: fetcher-api
        url-pattern: /fetcher/api/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="info">
                                        <AppenderRef ref="console" level="info"/>
                                    </Root>
                                </Loggers>
                            </Configuration>'
configuration-properties:
  fetcher:
    enabled: true